# Generated by Django 4.0.5 on 2022-06-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_admin_alter_userinfo_depart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='passwoer',
            new_name='password',
        ),
    ]
